export const GET_CAMPAIGN_LIST = 'GET_USER_LIST';
export const UPDATE_CAMPAIGN_TYPE = 'UPDATE_CAMPAIGN_TYPE';
export const SET_SELECTED_CAMPAIGN = 'SET_SELECTED_CAMPAIGN';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const CAMPAIGN_TYPE = {
    UPCOMING: 'UPCOMING',
    LIVE: 'LIVE',
    PAST: 'PAST',
};